### ISSUE TITLE
Multi svg to single pdf issue

### ISSUE THREAD

**Issue by hir3npatel** [Kozea/CairoSVG#119]
In the release version, seems like there is support for multi svg to single pdf, using a single file for input, having multiple children svg nodes in the xml.

When I run it as such, I get an error on 

> `/1.0.22/cairosvg/surface/__init__.py`

 line 427, object has no attribute page_sizes. I can't find any other reference to page_sizes, so if I go and delete that line, it seems to work fine (giving me multiple svg in one output pdf - one per page).

What is page_sizes in that context?

I invoke the example command with:

> cairosvg f1.svg -o f1.pdf

where f1.svg has:

```
<myroot>
<svg>...</svg>
<svg>...</svg>
...
</myroot>
```

**Comment by liZe** [comment]
> In the release version, seems like there is support for multi svg to single pdf, using a single file for input, having multiple children svg nodes in the xml.

It's true, and it's been removed as it was not compliant with the spec. I don't really want to have it back, as the code was a real mess.

If you want to generate multi-page PDFs, you can either:
- generate single-page PDFs and merge them with something like ghostscript,
- include the SVG files in a HTML document and generate a PDF with something like WeasyPrint,
- use HTML+CSS instead of SVG (that's the solution we chose in my company).

Is one of the solutions good for you?

**Comment by hir3npatel** [comment]
Solution 1 or 2 might work. I am pulling out svg's from a page full of google charts, and pdf them up. I can understand you want to remove it if it violates the spec. For now I will use the old release until I get a chance to put in solution 1 or 2. Thanks for the feedback.

**Comment by aziesemer** [comment]
I fixed this issue in pull request #199
