### ISSUE TITLE
Have problem em my system : AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'Matrix'

### ISSUE THREAD

**Issue by gsvimieiro** [Kozea/CairoSVG#151]
Hi,

My system have problem when create PDF with library Cairo : 
File "/home/giuliano.vimieiro/Projetos/sgp_desenv/sgp_desenv/src/sgp_dms/creator.py", line 281, in _get_matrix
    matrix = cairo.Matrix()
AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'Matrix'

I use Python version : 2.7.6
cairocffi==0.7.1
CairoSVG==1.0.22

Thanks

**Comment by liZe** [comment]
1. CairoSVG is not [Cairo](https://www.cairographics.org/) :smile:.
2. Looks like your problem is not in Cairo or in CairoSVG, but in the Cairo Python binding you're using. It depends on the import providing your `cairo` variable, something like [pycairo](https://cairographics.org/pycairo/) or [cairocffi](http://cairocffi.readthedocs.io/en/latest/).

**Comment by liZe** [comment]
@gsvimieiro Can I close this issue?

**Comment by gsvimieiro** [comment]
Yes Kozea thanks
Em 16/06/2017 11:24, "Guillaume Ayoub" <notifications@github.com> escreveu:
