### ISSUE TITLE
Text rendering regression in 2.3.0

### ISSUE THREAD

**Issue by JGiard** [Kozea/CairoSVG#233]
Hi,
I have an issue with an svg file where text does not render properly (nothing is readable).
However the conversion is working fine with cairosvg 2.2.1.

I'm using libcairo2 1.15.10. I install cairosvg on a clean virtualenv, convert the image, then upgrade cairosvg to 2.3.0 and convert again.

[2.3.0-regression.zip](https://github.com/Kozea/CairoSVG/files/2945030/2.3.0-regression.zip)

**Comment by liZe** [comment]
The problem is caused by your SVG having the `text-rendering: geometricPrecision` SVG property set. `geometricPrecision` means that "[the user agent shall emphasize geometric precision over legibility and rendering speed](https://www.w3.org/TR/SVG/painting.html#TextRenderingProperty)", meaning that letters get a "correct" size and position but can be unreadable at small sizes.

Note that you shouldn't get this problem too with renderers that don't rasterize text, such as browsers or even CairoSVG's PDF output. You only have the problem when the renderer's output is a raster format.

Of course, it's unfortunate to get such a low legibility. But unfortunately, it's our drawing library (called cairo) that handles this, and there's not much we can do. Actually, it just does what we ask it to do: if a "e" character must fit in a 3 by 5 pixels rectangle, it will find an unreadable solution to do so, without artificial solutions such as hinting and antialiasing that distort the layout to make letters readable.

The best solution is to remove the `text-rendering` property if you don't want to sacrifice legibility. If you increase the size of your image, the problem disappears too.

**Comment by JGiard** [comment]
Thank you for this clear explanation.

I'm curious though, was the change in behavior caused by a specific improvement in 2.3.0

**Comment by liZe** [comment]
> I'm curious though, was the change in behavior caused by a specific improvement in 2.3.0

Yes, it's related to the "Make text selectable on generated PDF files" entry of the changelog. Behind this change, we now use the real text renderer included in cairo, instead of transforming text into paths as we used to do. The text renderer is much powerful than a simple path as it can handle more features depending on the output: for example, when the output is a PDF file, it can include what's needed to have text that can be selected.

For your example, when the output is a raster image format, the renderer can improve geometric precision (knowing the exact resolution of the output image), reducing text readability.
