### ISSUE TITLE
svg2png is crashing on certain files

### ISSUE THREAD

**Issue by theelk801** [Kozea/CairoSVG#241]
I'm trying to use svg2png to convert some files and it's crashing on certain files. [Here's one of them.](https://pastebin.com/cLbnwBHE)

**Comment by theelk801** [comment]
Update: it seems to not be an issue when I specify the output width and height, which is fine for my use case.

**Comment by liZe** [comment]
It crashes because your file has no fixed size, and its viewbox proposes a 23'127px × 23'285px size (about 540 Mpx). That's huge! Even my image viewer crashes with this file.

Browsers can display this kind of SVG files because [they negotiate the concrete image size](https://www.w3.org/TR/css3-images/#object-negotiation). They actually do the same as you do when you give output width and height to CairoSVG.

But.

Actually, **your sample is successfully converted with CairoSVG in less than 30 seconds and 1.35GB of RAM on my (pretty good) computer**. Many applications (including my image viewer and Google Chrome) refuse to open the generated PNG because it's really big, but ImageMagick has no problem with it and can generate this beautiful thumbnail:
![thumbnail](https://user-images.githubusercontent.com/952243/58599006-cbe84d80-827e-11e9-85af-9044698c3bcb.png)

So… As far as I can tell, CairoSVG has no problem with this kind of images … as long as you give it enough time and memory to handle them :smile:. And it's pretty cool to see it generate huge PNG files that Chrome refuses to draw.
