### ISSUE TITLE
Difficulty running/installing CairoSVG python package on any platform

### ISSUE THREAD

**Issue by jpach01** [Kozea/CairoSVG#253]
I'm running a Windows 10 virtual environment with Anaconda. I'm using DrawSVG for python3, which depends on CairoSVG to rasterize SVG images. When I installed DrawSVG, CairoSVG also got installed. But when I went to run any code using DrawSVG it always prints this warning:
```
RuntimeWarning: CairoSVG will need to be installed to rasterize images: Install with `pip3 install cairosvg`
  warnings.warn(msg, RuntimeWarning)
```
Thinking that CairoSVG didn't install properly I went ahead and run `pip3 install CairoSVG`, with no success. Tried uninstalling `pip3 uninstall CairoSVG` and installing again but got nothing different. So, as suggested I tried installing some other packages that depend on CairoSVG like WeasyPrint. Got nothing different either so I tried in a different laptop running Ubuntu, in a VM with MacOS, in the WSL with Ubuntu, and still couldn't manage to get DrawSVG to rasterize svg files because it was missing CairoSVG after having installed all the package dependencies.

**What I tried at the end is one long installation command that is mentioned in the [WeasyPrint documentation for Ubuntu](https://weasyprint.readthedocs.io/en/latest/install.html#debian-ubuntu) on the WSL and it finally worked.**
```
sudo apt-get install build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
```
I haven't touched it since because *if it works, don't touch it* and it still working but it still was a pain to get it running. If I knew how these things work I'd edit the docs for CairoSVG to give at least minimal detail (preferably more than that) on how to install it, but I'm still learning so I'd hope someone who knows could do that and alleviate the process. Any constructive comment is appreciated.

**Comment by liZe** [comment]
As you can see in [this file](https://github.com/cduck/drawSvg/blob/bab21b78cc0e4c01ebb4371f24ab36781bc4e8d2/drawSvg/raster.py) of the DrawSVG package, the message is printed when there's a problem with CairoSVG. This error message should be printed when the package could not have been imported (`ImportError`).

The problem is that it is also printed when there's an `OSError`. This OS error happens when CairoSVG cannot find the module called Cairo. The Cairo module is not a Python module and thus cannot be installed with `pip`.

So:

1. CairoSVG is installed when you install DrawSVG.
2. CairoSVG can't find Cairo.
3. DrawSVG prints a misleading error message.
4. Reinstalling CairoSVG with pip doesn't fix the problem.
5. Your `apt-get` command installs Cairo, fixing the problem.
6. DrawSVG works.

The best solution is probably to open an issue on DrawSVG, asking them to print a better error message when an `OSError` is raised. **CairoSVG was installed since the beginning**, but DrawSVG hides the real error message you get when you try to import it.

> If I knew how these things work I'd edit the docs for CairoSVG to give at least minimal detail (preferably more than that) on how to install it

I think that the current documentation is pretty clear:
> CairoSVG and its dependencies may require additional tools during the installation: a compiler, Python headers, Cairo, and FFI headers. […] If you don’t know how to install these tools, you can follow the simple steps of WeasyPrint’s installation guide.

That's the proposed solution, and that's what fixed your problem.

If there's anything I should change in the documentation, please tell me, I'll do my best!

**Comment by jpach01** [comment]
Thank you for your time and patience. As you say it's the misleading warning message that led me to think that the source of the problem was the installation of CairoSVG. Therefore I only thought that it was CairoSVG that wasn't installing properly and didn't think of searching how to install Cairo instead. You've clarified excellently the situation and made me realise that the documentation was stating these things correctly, but I was looking at it with the perspective that CairoSVG was wrong. I failed to notice that as soon as I installed Cairo the problem was solved (mainly because I didn't realise I was installing Cairo in the first place).
Regarding the documentation, since most of the effort of installing CairoSVG relies on installing Cairo, why not have the same instructions on how to install it as there are in WeasyPrint? It's true that WeasyPrint install Cairo, but I didn't want to install WeasyPrint in the first place as I'm not using it. I'm suggesting something like this:

> ### [Installation](https://cairosvg.org/documentation/#installation)
> CairoSVG is available on PyPI, you can install it with pip:
> `$ pip3 install cairosvg`
> The current version of CairoSVG requires at least Python 3.5, it doesn’t work with Python 2.x. Older versions of CairoSVG (1.x) work with Python 2.x, but they’re not supported anymore.
> 
> CairoSVG and its dependencies may require additional tools during the installation: a compiler, Python headers, Cairo, and FFI headers. These tools have different names depending on the OS you are using, but:
> - on Windows, you’ll have to install Visual C++ compiler for Python and Cairo. Here's how:
> ![image](https://user-images.githubusercontent.com/44058413/65608597-6135ed00-dfa6-11e9-9554-f6e2e82616d8.png)

Thanks again. Keep up the good work!

**Comment by liZe** [comment]
> I'm suggesting something like this:

Yes, that would be an ideal solution, but the problem is that it's hard to keep up to date. There's a lot of work done in WeasyPrint's documentation to make it easier to read, I can't update CairoSVG's documentation each time WeasyPrint's one is changed :unamused:.

> Thanks again. Keep up the good work!

You're welcome, have fun with DrawSVG (and CairoSVG :wink:).
