### ISSUE TITLE
svg2svg in Python3 scales output incorrectly

### ISSUE THREAD

**Issue by acabal** [Kozea/CairoSVG#262]
Hello!

We're trying to use `svg2svg()` to take a fairly simple SVG with `<text>` elements, and output an SVG with the text converted to paths.

It seems like converting text to paths works fine. However the output image has a different canvas size than the input image, and the text appears to be scaled down.

In the input file, we only define a viewbox and not a height/width. But in the output file, height/width is included in `pt` units, and the viewbox has been shrunk.

If we specify the `dpi=90` option, the output file appears to be the correct canvas size. However, the text is off-center.

Here is the code we're using:

````python
import cairosvg

# Output a file that appears to be scaled down and the wrong canvas size, 1313x319 instead of 1400x340
cairosvg.svg2svg(url="/path/to/titlepage.svg", write_to="/path/to/output.svg")

# Output a file that is the right canvas size, but text is off-center.
cairosvg.svg2svg(url="/path/to/titlepage.svg", write_to="/path/to/output.svg", dpi=90)
````

Using the `output_height` and `output_width` parameters doesn't change the output.

GitHub doesn't allow SVG attachments, but you can download the file we're using here: https://standardebooks.org/ebooks/algis-budrys/short-fiction/images/titlepage.svg

Font used in the SVG is here: https://github.com/theleagueof/league-spartan/blob/master/LeagueSpartan-Bold.otf

**Comment by acabal** [comment]
After some more investigation, it looks like the off-center output might be due to the `letter-spacing` CSS property. The cairosvg docs say that letter-spacing is not supported; but I'm not sure if that refers to CSS or to some font property. If CSS letter-spacing isn't supported, is that on the roadmap?

But, it's still a mystery as to why the output file is scaled down when the `dpi` option isn't specified.

**Comment by acabal** [comment]
One more update, it looks like with `letter-spacing`, the output SVG has `letter-spacing` correctly applied; it's just not centered correctly. So a quick and dirty fix for us would be to parse each line and move the entire line left by `( (len(line) - 1) * letter_space_in_px) / 2`. Doing this seems to give us roughly the output we're expecting.

**Comment by liZe** [comment]
Hello, and thank you for this bug report!

> If we specify the `dpi=90` option, the output file appears to be the correct canvas size. However, the text is off-center.

I think that it’s because Cairo always give a size (with units) to generated SVG files. Using the `dpi` option is a solution to set this output size, as you want t set a ratio between real-life units (points) and SVG pixels.

> However, the text is off-center.

Yes, that’s a bug.

> After some more investigation, it looks like the off-center output might be due to the `letter-spacing` CSS property.

It is. Contrary to what’s said in the documentation, `letter-spacing` is supported by CairoSVG, but it breaks text alignment.

> So a quick and dirty fix for us would be to parse each line and move the entire line left by `( (len(line) - 1) * letter_space_in_px) / 2`. Doing this seems to give us roughly the output we're expecting.

Yes, we have to do something like that.

**Comment by liZe** [comment]
2 bugs are fixed thanks to your issue!

- letter spacing was applied before first letter
- alignment was wrong when letter spacing was set

I’ll find the time to release next version in March!

**Comment by acabal** [comment]
Thanks!

Is there a way to get output image to be the same size as the input image, without using a DPI magic number?

Also, is there a way to get the output SVG to remain in px units, instead of being converted to pt? Even specifying SVG height/width in px doesn't everything being converted to pt in the output.

**Comment by liZe** [comment]
> Thanks!

No problem!

> Is there a way to get output image to be the same size as the input image, without using a DPI magic number?

It’s complicated. Let’s try to give a simple answer with a lot of details!

Your original SVG file has no size, because there’s no width and no height set on the `svg` tag.

There’s just a `viewBox`. Numbers in `viewBox` are measured in user units, that are not real-life units like inches or millimeters. But, as there’s no size and as we need one to generate the image, its values are used to give a size, assuming that 1 user unit = 1 pixel.

So, when you generate a PNG, its size is 1400px × 340px, because the `viewBox` is `0 0 1400 340`.

When you generate an SVG file with CairoSVG, it has to have a size because CairoSVG needs a size (it generally generates PNGs and PDFs with real-life sizes). The size of your document is 1400px × 340px.

1in = 72pt (as defined by the specification)
1in = 96px (as defined by the DPI value, CairoSVG’s default value is 96)

It means that your document is (1400 ÷ 96 × 72)pt × (340 ÷ 96 × 72)pt = 1050pt × 255pt. That’s exactly what’s in the SVG file generated by CairoSVG. Chang the DPI value and you’ll get a different result.

Your original SVG has no size. Image viewers have to give it a size to draw it, they use the DPI value they want, probably 90 for your SVG viewer (here’s where your magic number comes from!). If you want to be sure to get the same size, set `width` and `height` on your `svg` tag using real-life units, otherwise you’ll depend on the DPI value of your viewers.

(Pixels as defined by [the SVG specification](https://www.w3.org/TR/SVG11/coords.html#Units) are not real-life units, they are not the pixels of your screen, they actually equal to user units as said earlier.)

**Short answer: Give a size to your original SVG file, add `width="1120pt" height="272pt"` to your `svg` tag.**

> Also, is there a way to get the output SVG to remain in px units, instead of being converted to pt? Even specifying SVG height/width in px doesn't stop everything from being converted to pt in the output.

There’s [a technical way in recent values of Cairo](https://www.cairographics.org/manual/cairo-SVG-Surfaces.html#cairo-svg-surface-set-document-unit), but I think that it’s not a good idea. CairoSVG is designed to generate images with sizes set in real-life units, and changing this rule especially for SVG files will only add more complexity. There are too many arguments (`dpi`, `scale`, `width`, `output-width`…) that are already hard to understand for users (and were sometimes added against my will!), adding one more is not a solution for me.

And of course, always using pixels instead of points would break rendering for images with real-life units sizes :cry:.

**Comment by acabal** [comment]
Thanks for the detailed answer!

One last unrelated question: I saw in the docs that Cairo has notoriously bad font support. Do you foresee Cairo improving its font kerning support any time soon?

The generated SVGs are very good except that Cairo has clearly discarded kerning, which is unfortunate and might be enough for us to stick with Inkscape for text -> path conversion for now.
