### ISSUE TITLE
Sample for REDoS is not working

### ISSUE THREAD

**Issue by elisaburato** [Kozea/CairoSVG#313]
I'm trying to reproduce the REDoS of CVE-2021-21236 by using the sample reported [here](https://github.com/Kozea/CairoSVG/security/advisories/GHSA-hq37-853p-g5cf)
`'<svg width="1" height="1"><rect fill="rgb(' + (' ' * 3456) + ';"/></svg>'`
with CairoSVG 2.4.
I have the following error:

```
Traceback (most recent call last):
  File "\cairosvg-script.py", line 9, in <module>
    sys.exit(main())
  File "\cairosvg\__main__.py", line 83, in main
    SURFACES[output_format.upper()].convert(**kwargs)
  File "\cairosvg\surface.py", line 146, in convert
    instance = cls(
  File "\cairosvg\surface.py", line 212, in __init__
    self.draw(tree)
  File "\cairosvg\surface.py", line 449, in draw
    self.draw(child)
  File "\cairosvg\surface.py", line 420, in draw
    self.context.set_source_rgba(*color(paint_color, fill_opacity))
  File "\cairosvg\colors.py", line 236, in color
    r, g, b = tuple(
  File "\cairosvg\colors.py", line 237, in <genexpr>
    float(i.strip(' %')) / 100 if '%' in i else float(i) / 255
ValueError: could not convert string to float: "' '+ (' ' * 3456"
```

**Comment by liZe** [comment]
Hi!

You can’t reproduce because CVE-2021-21236’s example is Python code, not plain SVG.

If you want to reproduce the REDoS, you have to create an SVG file with this content:

```
<svg width="1" height="1"><rect fill="rgb(                       ;"/></svg>
```

but you have to add a lot of spaces after `rgb(`. For example, rendering on my computer takes:
- ~0.1s for 100 spaces
- ~0.7s for 1,000 spaces
- ~670s (!) for 10,000 spaces

With version 2.5.1, it always takes ~100ms. The SVG file with 10,000 spaces is attached.

[fail.txt](https://github.com/Kozea/CairoSVG/files/5950396/fail.txt)
