### ISSUE TITLE
Image corrupted

### ISSUE THREAD

**Issue by janetkok** [Kozea/CairoSVG#335]
![image](https://user-images.githubusercontent.com/45690357/123914407-46608b80-d977-11eb-9756-63f372009100.png)
![2105182_6](https://user-images.githubusercontent.com/45690357/123914422-482a4f00-d977-11eb-8126-59d14b10b1b4.png)

Above is the original image
Below is the corrupted image
I did a simple conversion using the following code:
cairosvg.svg2png(url= svg_file, write_to= png_file)

Attached is the original file

[corrupt.zip](https://github.com/Kozea/CairoSVG/files/6738845/corrupt.zip)

**Comment by liZe** [comment]
Hello!

Thank you for this bug report.

The bug is caused by `text-rendering="geometricPrecision"`, and it’s [a bug in Cairo](https://gitlab.freedesktop.org/cairo/cairo/-/issues/152). The bug is pretty old, and it may take a lot of time to get a fix 😒. Removing the property from the SVG is probably the best workaround for now.
