### ISSUE TITLE
Font overlap

### ISSUE THREAD

**Issue by luoyu-123** [Kozea/CairoSVG#341]
When I use CairoSVG to convert svg to pdf file, the fonts overlap. Is there any way to solve this problem?
This is the effect of svg：
![image](https://user-images.githubusercontent.com/59160360/129856905-b219464d-8761-41a4-9684-0d50920ccf16.png)
This is the effect after converting to a pdf file：
![image](https://user-images.githubusercontent.com/59160360/129857013-6862085c-a744-4eb9-a4be-33c4d7a78af0.png)
svg compressed file--
[2_1_5.zip](https://github.com/Kozea/CairoSVG/files/7005428/2_1_5.zip)

**Comment by liZe** [comment]
Hello, and thank you for your report.

Could you please share the original SVG file?

**Comment by luoyu-123** [comment]
I'm very sorry, I uploaded the wrong file, and I am ashamed of my stupid behavior. This is the svg file and the font package used in it (note: the environment I use is the windows development environment, I don’t know if it is related to this)
This is the source file：
[svgFile.zip](https://github.com/Kozea/CairoSVG/files/7011168/svgFile.zip)
Thank you for your help！！

**Comment by liZe** [comment]
No problem!

I don’t have the problem with your file, here’s what I get:
![2_1_5](https://user-images.githubusercontent.com/952243/130135708-1a049647-65e2-480d-83de-d96f0ccd071a.png)

Your problem is actually the same as Kozea/WeasyPrint#1343. It’s [a bug in Cairo](https://gitlab.freedesktop.org/cairo/cairo/-/issues/449) that’s already fixed but not released. You’ll find different solutions (downgrade Cairo, apply a patch…) in WeasyPrint’s issue to fix this problem.

**Comment by luoyu-123** [comment]
Thank you for your help

**Comment by luoyu-123** [comment]
My system default encoding is gbk format。
The picture below is the system-related configuration
![image](https://user-images.githubusercontent.com/59160360/131201899-1088c818-942a-4e24-b61d-291bd6f5f6fb.png)
The reason why the file name should be in Chinese

*****************************
The figure below is about the python environment and the version of GTK
![image](https://user-images.githubusercontent.com/59160360/131202238-c295254f-2142-4fe3-9e2b-60e0a968fef8.png)
![image](https://user-images.githubusercontent.com/59160360/131202250-9345014e-9e49-4bc5-9460-f52d348099fe.png)
![image](https://user-images.githubusercontent.com/59160360/131202286-d59236c2-0dbc-46b5-8de4-3b26b61ada59.png)
GTK3 also has this problem, so I am installing GTK2 now. This is the solution I saw in Stack Overflow, but it still didn’t work.

**Comment by luoyu-123** [comment]
I don't know if it is because of the Chinese encoding. I have not encountered such problems in the Linux system. But in the window system, I tried 3 windows system computers and encountered this problem, so that the reinstallation of the system did not improve

**Comment by liZe** [comment]
I’ve tried to find a solution for this problem, but it really looks like a bug in Pango with Windows’ Chinese encoding.

As a last resort, you can try to launch "pango-view" (installed with GTK+) to display Chinese text, and see if you get something wrong. It’s unlikely, because drawing text seems to work (what doesn’t is drawing text outline), but if you get extra spaces, at least you can give Pango devs a simple use case to fix their bug.

If "pango-view" works correctly, then I’m sorry but I really don’t know how to help you :cry:. You could try to talk with Pango devs to find a solution.

**Comment by luoyu-123** [comment]
Thank you very much for your kind help
Best wishes!

**Comment by liZe** [comment]
Did you try `pango-views` on your Windows computer?

**Comment by luoyu-123** [comment]
Hello, it seems that there is a problem when installing pango. I cannot use the pango-view command on the command line (I have installed GTK related dependencies). I am still looking for related solutions. I am the first Use these things again, if you offend, please forgive my stupidity

**Comment by liZe** [comment]
No problem, take your time.

(And you’re not stupid!)
