### ISSUE TITLE
Error when converting svg to pdf

### ISSUE THREAD

**Issue by luoyu-123** [Kozea/CairoSVG#344]
When I was converting svg to pdf, the following error occurred, the status code prompt is 11, and there is a write stream output error
This is the picture：
![image](https://user-images.githubusercontent.com/59160360/131622341-7dd999e3-0656-4ccc-8b47-4e5dfc7e6973.png)

**Comment by luoyu-123** [comment]
This is the svg file
[3_1_5.zip](https://github.com/Kozea/CairoSVG/files/7088757/3_1_5.zip)

**Comment by liZe** [comment]
Hello!

This file works fine for me.

[3_1_5.pdf](https://github.com/Kozea/CairoSVG/files/7100214/3_1_5.pdf)

The error you have may be caused by multiple reasons, but it generally means that you don’t have the right to write the file. Maybe you want to generate your PDF file in a folder that doesn’t exist, or where you don’t have the right to create files?

**Comment by luoyu-123** [comment]
Hello, I can be sure that my folder has permission to create pdf files. Very grateful for your help

**Comment by liZe** [comment]
Maybe there’s something wrong in the filename. Could you try to generate a file with only ASCII in the full filename?

**Comment by luoyu-123** [comment]
I think I found the root cause. The specific reason is that in the svg code I generated, I gave an absolute value to the rotate assignment in the transform attribute to generate the error. The same file name can be converted after the assignment is changed again. As a pdf file, I am very sorry for the trouble. Thank you
