### ISSUE TITLE
CAIRO_STATUS_WIN32_GDI_ERROR

### ISSUE THREAD

**Issue by o-sapov** [Kozea/CairoSVG#377]
On windows 10, python 3.8 I'm getting:

`cairocffi.CairoError: cairo returned CAIRO_STATUS_WIN32_GDI_ERROR: b'error occurred in the Windows Graphics Device Interface'`

When applying:
```python
cairosvg.svg2pdf(
    url="file.svg", write_to="file.png")
```

Same on the command line.

`cairosvg                  2.6.0              pyhd8ed1ab_0    conda-forge `

**Comment by liZe** [comment]
Hi!

Maybe there’s a problem with the fonts installed on your system. Is your setup a fresh Windows, or is it the computer you use for your daily work, or maybe a virtual machine?

If you could try the same code on another computer, or if you could try another (simple) SVG file, it would be helpful to find where the problem comes from.

**Comment by liZe** [comment]
It’s probably a bug in Cairo: https://gitlab.freedesktop.org/cairo/cairo/-/issues/530

**Comment by Daniel63656** [comment]
I have the same problem. Using cairosvg for simpler svg works, but using musical svg (rendered with verovio) fails. I installed the used Bravura and BravuraText fonts on my windows system, no effect.

**Comment by liZe** [comment]
@Daniel63656 As explained above, it’s probably a bug in Cairo. Maybe you can ask Cairo devs if there’s anything that can be done to fix this bug.
