### ISSUE TITLE
closing the path for ellipse (and circle)?

### ISSUE THREAD

**Issue by leejjoon** [Kozea/CairoSVG#403]
Thanks for the great package first of all.

I encountered an what seems to an edge case where the rendered result is incorrect. This seems to be related with the fact that the cairosvg converts the circles and ellipse to a path which is not closed.

https://github.com/Kozea/CairoSVG/blob/d9ce00ac48a038b4d97f8639574416b4e5d5721c/cairosvg/shapes.py#L36

In most case I don't think this is a problem, but I get incorrect result if I process the svg output of cairosvg with picosvg (https://github.com/googlefonts/picosvg), which translate stoke to fill. Adding `surface.context.close_path()` solves the issue but not sure if it will introduce problems for surfaces other than the svg one.

**Comment by liZe** [comment]
Hi,

Thanks for this report!

You’re right, we should call `close_path`! It’s also true with `circle` just above.

Do you want to open a pull request? I can add the fix myself if you prefer.

> Adding `surface.context.close_path()` solves the issue but not sure if it will introduce problems for surfaces other than the svg one.

It slightly changes the rendering, I can’t even see the difference, but one test fails because the result is not 100% what it was (yes, our unit tests as stupid.) But no problem, as the rendering is OK I’ll just change the test after.

**Comment by leejjoon** [comment]
Thanks for the quick response.
And please go ahead and fix this issue.

Thanks!
