### ISSUE TITLE
License of W3C test suite

### ISSUE THREAD

**Issue by fladi** [Kozea/CairoSVG#75]
The file `test/README.rst` states that the test suite assets are released by the W3C under a 3-clause BSD license. However the [W3C](http://www.w3.org/Graphics/SVG/WG/wiki/Test_Suite_Overview) states in its test suite overview, that they use the [W3C Document License](http://www.w3.org/Consortium/Legal/copyright-documents).

This is an issue for me as distributions such as Debian cannot include assets under such a license in its official package archive. Could anyone clarify as to which license really applies to the files in `test/`?

**Comment by liZe** [comment]
That's not really clear :/.

(Before anything else: CairoSVG is distributed on PyPI **without** tests because these tests track regressions during software development and do not really test that the software actually works after being installed. I think that packagers should use the package on PyPI (without tests), not the ones given by GitHub (with tests).)

Here's what's on the page you give:
> All tests have been submitted under the Policies for Contribution of Test Cases to W3C, copyright and test suite distribution are governed by the W3C Document License and the W3C Member agreement.
http://www.w3.org/Consortium/Legal/2008/04-testsuite-copyright

Here's what's on the page linked by the previous quote (Policies for Contribution of Test Cases to W3C):
> Distribution of W3C Test Suites is governed by the Licenses for W3C Test Suites.
(http://www.w3.org/2004/10/27-testcases.html#commentary)

Here's what's on the page linked by the previous quote (Licenses for W3C Test Suites):
>Licenses for distribution of W3C Test Suites should satisfy two goals:
1. Enable developers to use test cases easily, and promote software development and bugtracking.
2. Enable a W3C Working Group to create a branded, "Authoritative W3C Test Suite" to reflect the group consensus process, and to promote interoperability and stability of performance claims.

>To achieve these goals, W3C makes available Test Suites under two distinct licenses for two mutually exclusive uses:
1. a 3-clause BSD License for software development, bugtracking, and other applications that do not require assertions of performance to the public or implied claims of conformance to a W3C Specification. See summary of 3-clause BSD License.
2. a W3C Test Suite License for an Authoritative W3C Test Suite or when claims of performance with respect to a specification are required. See summary of W3C Test Suite License.
(http://www.w3.org/Consortium/Legal/2008/04-testsuite-copyright)

What I understand from these contradictory quotes is that the tests are generally distributed under the W3C Test Suite License, but can be distributed under the 3-clause BSD License for software development and bugtracking. CairoSVG is exactly in this second case, distributing the test files is clearly for a software testing purpose, so the BSD License can be used.

**Comment by fladi** [comment]
Thanks for bringing a bit of clarity into this. I already disabled the tests in the Debian package (which I maintain). I'll also start pulling new upstream releases from PyPI instead of Github. Will there ever be deployment tests? Would be nice to have automatic tests while building the package from source …

**Comment by liZe** [comment]
That's a good idea, I have created a new ticket!
