### ISSUE TITLE
Scaling question

### ISSUE THREAD

**Issue by Chris-May** [Kozea/CairoSVG#83]
I'm looking through the documentation and code, and I'm trying to figure out if there's a way to scale the svg up to make a png file.

It appears the svg code I'm passing in is only 65px wide, which is much too small. Is there a way to scale it to be, say, 300px?

**Comment by Chris-May** [comment]
Ah... I found I could change `device_units_per_user_units` in `PNGSurface` to make the PNG bigger.

I guess that's probably going to have to be the way to do that for now?

**Comment by liZe** [comment]
The SVG format gives the possibility to make the size of the generated file related to properties given to the rendering tool, but that's sometimes hard to understand. CairoSVG doesn't provide hacks (something like a 'zoom' option), because creating good SVG files (or modifying them to make them fit your needs) is definitely better than just randomly playing with random variables in the code :wink:.

So, here are the important things to understand:

1. The concept of size is different for different file formats. Raster graphic formats (PNG for example) use the pixel as the intrinsic size unit, whereas some other vector graphic formats (PDF for example) use physical size units such as points, inches or millimeters. It means that the physical size of a PNG depends on the tool used to render it, and that the number of pixels used to render a PDF depends on the tool used to render it.

2. The 'svg' tag can have a width and a height given in pixels or in physical sizes.
  - When you transform a SVG file into a PNG file with CairoSVG, if the size given in the 'svg' tag is given in pixels, then the size of the generated PNG is the size given in the 'svg' tag, and CairoSVG can't change it. 1px in the 'svg' tag is 1px in the PNG file.
  - When you transform a SVG file into a PDF file with CairoSVG, if the size given in the 'svg' tag is given in physical units, then the size of the generated PDF is the size given in the 'svg' tag, and CairoSVG can't change it. 1mm in the 'svg' tag is 1mm in the PDF file.

3. You can give the power to change the size of the generated image to CairoSVG, using the 'dpi' parameter that sets a ration between inches and pixels. Just use a physical size in the 'svg' tag, and the number of pixels of the generated PNG will depend on the 'dpi' ratio! And of course, if you use pixels in 'svg', the number of millimeters of a generated PDF file will depend on the 'dpi' ratio too.

4. With the current git version of CairoSVG, you can also give the size of the 'svg' tag in percentages. This percentage is applied to a 'container size' that can be given to CairoSVG thanks to the 'width' and 'height' options. So, if you want your SVG files to have no intrinsic sizes and give the tool the power to set this size, just use percentages, that will fit all your needs!

An example, if you want to change the size of a generated PNG file:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="1in" height="1in">
  <rect x="10" y="10" width="80" height="80" fill="red" />
</svg>
```

Use a 'dpi' value of 10 and you'll get a 10px × 10px image, use 100 and you'll get a 100px × 100px image. That's THE SOLUTION™!

PS: You can also play with ratios and zooms using the 'viewBox' and 'preserveAspectRatio' attributes, but that's another story. The [SVG reference](http://www.w3.org/TR/SVG/) is sometimes hard to understand, but you can spend some time reading it if you want to understand all its powerful (and unknown) features!

**Comment by ricardobeat** [comment]
The `--dpi` argument doesn't seem to be working in 1.0.20. 

```xml
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="387px" height="89px" viewBox="0 0 387 89" > ...
```
`cairosvg cairosvg logo.svg --dpi=1000 -o logo.png`

Still generates a 387x89px image.

**Comment by ricardobeat** [comment]
By the way this is not about "good" SVG files or not - when you want to generate PNG fallback images, for agents that do not support SVG, you might want them to have a higher resolution so they can still be used at different sizes.

**Comment by liZe** [comment]
> The --dpi argument doesn't seem to be working in 1.0.20.

As explained above, a SVG with `width="387px"` will have a width of 387 pixels. The `dpi` option won't change that. This SVG **has a size in pixels**, and CairoSVG won't change it for formats whose intrinsic unit is the pixel, as PNG.

> By the way this is not about "good" SVG files or not - when you want to generate PNG fallback images, for agents that do not support SVG, you might want them to have a higher resolution so they can still be used at different sizes.

I understand what you want, having more pixels is useful when you want to generate PNG fallbacks. 

But, really, what you want is **a way to change the size of the image**, just like you'd ask a program to convert a 100×100px JPEG to a 200×200px PNG. CairoSVG doesn't provide this feature. The `dpi` option changes the ratio between pixels and inches, but it's not a `zoom` or `png-resolution` option.

**Comment by ricardobeat** [comment]
Hi @liZe. As you know the **S** in SVG stands for *Scalable* Vector Graphics, the comparison to JPEG doesn't make any sense as this is a vector format.

Having a width defined in px is merely a presentation constraint, the SVG itself doesn't *have a size*. Nowadays even the `px` is a relative unit - if you look at that same SVG in a retina screen, it will actually be rendered with a width of `774` pixels, so a similar resolution scaling applies as when using relative units like inches.

I now understand the DPI will only set the DPI ratio for the generated image. Since a zoom/ratio option is missing I thought that could have been the way to do it. So the question would be, is there any interest in implementing a function like rsvg-convert's `zoom` to arbitrarily rescale the output? It seems to me that a  vector image processing tool that is not resolution independent kind of defeats it's own purpose.

**Comment by liZe** [comment]
I agree with you on many parts. "1px" in an SVG file is not one pixel on the screen. This feature can be useful, for sure.

Just because of https://xkcd.com/386/, let me be clear: (take a break before reading this, it'll be long!)

> Having a width defined in px is merely a presentation constraint, the SVG itself doesn't have a size.

It *does*.

It's not just in my crazy imagination, it's in [the specification](http://www.w3.org/TR/SVG/struct.html#SVGElement), the `width` and `height` attributes define the intrinsic size of the SVG.

It's hard to admit. I've spent countless days reading this specification (and other interesting ones such as CSS and CalDAV), and one of the important things I've learnt is that the formats are not what **I** think, they are **what's been written in the specification**. Each time I've tried to implement things *my way* (you know, the moment when "these specification guys are stupid and are on LSD"), it was a nightmare at the end.

You have the feeling that "the SVG itself doesn't have a size", and that's easy to understand why, your assumption is even logical, it's scalable, there's no pixel, etc. But that's just a feeling, and the truth is different.

> Nowadays even the px is a relative unit - if you look at that same SVG in a hi-res screen, it will actually be rendered with a width of 774 pixels, so a similar resolution scaling applies as when using relative units like inches.

That's an interesting example. SVG mainly relies on CSS for the "pixel" definition, and you're right about this: `1px` in SVG is not the same as a device pixel. It's not a "nowadays" problem:

> Pixel units, as used in the last rule, are relative to the resolution of the canvas, i.e. most often a computer display. If the pixel density of the output device is very different from that of a typical computer display, the UA should rescale pixel values. The suggested reference pixel is the visual angle of one pixel on a device with a pixel density of 90dpi and a distance from the reader of an arm's length. For a nominal arm's length of 28 inches, the visual angle is about 0.0227 degrees.

That was CSS 1, released in 1996 :open_mouth:!

It was the first step to [CSS 3 Values and Units](http://www.w3.org/TR/css3-values/#absolute-lengths), backported to CSS 2.2. Here is the new definition:

> For a CSS device, these dimensions [in, cm, mm, pt, pc, px] are either anchored (i) by relating the physical units to their physical measurements, or (ii) by relating the pixel unit to the reference pixel. For print media and similar high-resolution devices, the anchor unit should be one of the standard physical units (inches, centimeters, etc). For lower-resolution devices, and devices with unusual viewing distances, it is recommended instead that the anchor unit be the pixel unit. For such devices it is recommended that the pixel unit refer to the whole number of device pixels that best approximates the reference pixel.
> The reference pixel is the visual angle of one pixel on a device with a pixel density of 96dpi and a distance from the reader of an arm's length. For a nominal arm's length of 28 inches, the visual angle is therefore about 0.0213 degrees. For reading at arm's length, 1px thus corresponds to about 0.26 mm (1/96 inch).

So we now have 1px = 1/96in, removing the need of a `dpi` parameter. Hmmmm.

> Note that this definition of the pixel unit and the physical units differs from previous versions of CSS. In particular, in previous versions of CSS the pixel unit and the physical units were not related by a fixed ratio: the physical units were always tied to their physical measurements while the pixel unit would vary to most closely match the reference pixel. (This change was made because too much existing content relies on the assumption of 96dpi, and breaking that assumption breaks the content.)

A fabulous example of "people are so stupid that we MUST rewrite specifications to become stupid too" :wink:.

(Just for the record: it's not a "relative unit", it's called "absolute length units" by the CSS gods, "absolute" meaning that they're relative to their "output environment". Who said they were on LSD?)

So, **the feature you really want is to define the ratio between the reference pixel and the device pixel**, the latter being real pixels for PNG files. This ratio would useless for formats relying on physical units.

But really, after reading the specification, it's hard to tell that using 1 reference-pixel = 1 device-pixel. Everything is made in SVG to allow users do define no intrinsic size if there's no need to. A SVG file with no intrinsic size can keep an instrinsic ratio, can define a resizing strategy, etc. It can be embedded in other `svg` tags where it can be transformed. It can be embedded in HTML `object` tags where it can be transformed.

> Nowadays even the px is a relative unit - if you look at that same SVG in a hi-res screen, it will actually be rendered with a width of 774 pixels, so a similar resolution scaling applies as when using relative units like inches.

A fixed 96dpi parameter everywhere (TVs, phones, whatever) when it's not the reality was a stupid choice made by lazy people, leading to all that tookit and CSS crap. But I could understand that, after taking sufficient quantities of alcohol and drugs. People being lazy, taking stupid decisions. OK. Why not.

> It seems to me that a vector image processing tool that is not resolution independent kind of defeats it's own purpose.

Again, if a resolution is a ratio between pixels and real life units, then CairoSVG is not resolution independant.

But now is defined the new `ppp` unit, the `pixel per pixel`, where a "device resolution" parameter would have been possible. And now you're one of the `pixel per pixel` defenders. Welcome to the club :+1:. **You want a parameter definig a ratio between pixels and pixels.** Don't be shy!

Yes, I'll accept a pull request for this feature, because it's useful, and because "the reality blah blah blah phones hi-res screens blah blah Retina Illuminati blah blah blah". Yes, you're not responsible for this situation, toolkits depending on pseudo-pixels, CSS depending on pseudo-pixels, pixels depending on pseudo-pixels. I'm not angry against you at all, I even *like* you, really. But.

Let's remember. On Windows 95, there was an option called "screen resolution" that was scaling the whole interface. Yes, even images, even buttons, almost everything. That was not perfect, but that was much better than the "scale" or "zoom" option we now have on our OSes. I swear. And at least, this ratio meant something, it had a unit.

Yes. I miss Windows 95. (I hope that my country will keep being a kind of democracy, or I may be killed for these words.)

> I now understand the DPI will only set the DPI ratio for the generated image.

My life has not been totally useless then.

**Comment by mrx23dot** [comment]
Given any svg file, how do I scale it to have 10cm  (canvas+content) height in Inkscape? (svg in - svg out)

I assume I have to somehow get the current height and width with the lib and scale it to 378 px with 'g transform'
(10cm = 378 px @ 96dpi)

Also where can I find the doc for using it as a python library?
https://cairosvg.org/documentation/ only contains cli doc.

**Comment by liZe** [comment]
> Given any svg file, how do I scale it to have 10cm (canvas+content) height in Inkscape? (svg in - svg out)

The easiest solution is just to change the `width` and `height` of the `svg` tag to set `10cm`. Assuming that the values used in your SVG don’t have units, it will be enough. You don’t need CairoSVG to do this, but a simple XML reader/writer (or a text editor 😁).

> Also where can I find the doc for using it as a python library?

The only public API is the `svg2*` functions. CairoSVG’s goal is to transform SVG images to other formats, not to modify them.

**Comment by mrx23dot** [comment]
Tried that, it only shrinks the canvas in inkscape not the content. Please find it attached.
Content is like:
`<path style="stroke:#FF0000; fill:none;" d="M379 244C361.917 255.856 366.858 273.103 369 291"/>`
full [test.zip](https://github.com/Kozea/CairoSVG/files/7503617/test.zip)

What's the go-to lib for svg modification for python?

**Comment by liZe** [comment]
> it only shrinks the canvas in inkscape not the content

Then you have to add a `viewBox` attribute to the `svg` tag, corresponding to the original size (`viewBox="0 0 780 1110"`).

**Comment by mrx23dot** [comment]
That works great, thank you!
Although I have to still manually calculate width, otherwise the canvas remains wide.
`<svg  width="7.02cm" height="10cm"   viewBox="0 0 780 1110"  preserveAspectRatio="xMinYMin meet"`
